package com.gumer.endo.entity;
// Generated May 17, 2016 5:50:10 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Doctors generated by hbm2java
 */
@Entity
@Table(name="doctors"
    ,schema="public"
)
public class Doctors  implements java.io.Serializable {


     private int id;
     private String firstName;
     private String lastName;
     private String fatherName;
     private String position;

    public Doctors() {
    }

    public Doctors(int id, String firstName, String lastName, String fatherName, String position) {
       this.id = id;
       this.firstName = firstName;
       this.lastName = lastName;
       this.fatherName = fatherName;
       this.position = position;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="first_name", nullable=false)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="last_name", nullable=false)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    
    @Column(name="father_name", nullable=false)
    public String getFatherName() {
        return this.fatherName;
    }
    
    public void setFatherName(String fatherName) {
        this.fatherName = fatherName;
    }

    
    @Column(name="position", nullable=false)
    public String getPosition() {
        return this.position;
    }
    
    public void setPosition(String position) {
        this.position = position;
    }




}


