package com.gumer.endo.entity;
// Generated May 17, 2016 5:50:10 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Nurses generated by hbm2java
 */
@Entity
@Table(name="nurses"
    ,schema="public"
)
public class Nurses  implements java.io.Serializable {

     
     private int id;
     private String firstName;
     private String lastName;
     private String fatherName;

    public Nurses() {
    }

    public Nurses( int id, String firstName, String lastName, String fatherName) {
       this.id = id;
       this.firstName = firstName;
       this.lastName = lastName;
       this.fatherName = fatherName;
    }
   
    @Id 
    @Column(name="id", unique=true)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="first_name")
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="last_name")
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    
    @Column(name="father_name")
    public String getFatherName() {
        return this.fatherName;
    }
    
    public void setFatherName(String fatherName) {
        this.fatherName = fatherName;
    }




}


