package com.gumer.endo.entity;
// Generated May 17, 2016 5:50:10 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Surveys generated by hbm2java
 */
@Entity
@Table(name="surveys"
    ,schema="public"
)
public class Surveys  implements java.io.Serializable {


     private int id;
     private int patientId;
     private Date date;
     private String surveyName;
     private String guideDiagnosis;
     private String guide;
     private String surveyType;
     private String anethesia;
     private String surgeonName;
     private String nurseName;
     private String protocol;
     private String protocolDescr;
     private String manipulation;
     private String conclusion;
     private String helicoTest;
     private String acidityTest;

    public Surveys() {
    }

    public Surveys(int id, int patiendId, Date date, String surveyName, String guideDiagnosis, String guide, String surveyType, String anethesia, String surgeonName, String nurseName, String protocol, String protocolDescr, String manipulation, String conclusion, String helicoTest, String acidityTest) {
       this.id = id;
       this.patientId = patiendId;
       this.date = date;
       this.surveyName = surveyName;
       this.guideDiagnosis = guideDiagnosis;
       this.guide = guide;
       this.surveyType = surveyType;
       this.anethesia = anethesia;
       this.surgeonName = surgeonName;
       this.nurseName = nurseName;
       this.protocol = protocol;
       this.protocolDescr = protocolDescr;
       this.manipulation = manipulation;
       this.conclusion = conclusion;
       this.helicoTest = helicoTest;
       this.acidityTest = acidityTest;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    


    @Temporal(TemporalType.DATE)
    @Column(name="date", nullable=false, length=13)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    
    @Column(name="survey_name", nullable=false)
    public String getSurveyName() {
        return this.surveyName;
    }
    
    public void setSurveyName(String surveyName) {
        this.surveyName = surveyName;
    }

    
    @Column(name="guide_diagnosis", nullable=false)
    public String getGuideDiagnosis() {
        return this.guideDiagnosis;
    }
    
    public void setGuideDiagnosis(String guideDiagnosis) {
        this.guideDiagnosis = guideDiagnosis;
    }

    
    @Column(name="guide", nullable=false)
    public String getGuide() {
        return this.guide;
    }
    
    public void setGuide(String guide) {
        this.guide = guide;
    }

    
    @Column(name="survey_type", nullable=false)
    public String getSurveyType() {
        return this.surveyType;
    }
    
    public void setSurveyType(String surveyType) {
        this.surveyType = surveyType;
    }

    
    @Column(name="anethesia", nullable=false)
    public String getAnethesia() {
        return this.anethesia;
    }
    
    public void setAnethesia(String anethesia) {
        this.anethesia = anethesia;
    }

    
    @Column(name="surgeon_name", nullable=false)
    public String getSurgeonName() {
        return this.surgeonName;
    }
    
    public void setSurgeonName(String surgeonName) {
        this.surgeonName = surgeonName;
    }

    
    @Column(name="nurse_name", nullable=false)
    public String getNurseName() {
        return this.nurseName;
    }
    
    public void setNurseName(String nurseName) {
        this.nurseName = nurseName;
    }

    
    @Column(name="conslusion", nullable=false)
    public String getConslusion() {
        return this.protocol;
    }
    
    public void setConslusion(String conslusion) {
        this.protocol = conslusion;
    }

    
    @Column(name="conscusion_descr", nullable=false)
    public String getConscusionDescr() {
        return this.protocolDescr;
    }
    
    public void setConscusionDescr(String conscusionDescr) {
        this.protocolDescr = conscusionDescr;
    }

    
    @Column(name="manipulation", nullable=false)
    public String getManipulation() {
        return this.manipulation;
    }
    
    public void setManipulation(String manipulation) {
        this.manipulation = manipulation;
    }

    
    @Column(name="conclusion", nullable=false)
    public String getConclusion() {
        return this.conclusion;
    }
    
    public void setConclusion(String conclusion) {
        this.conclusion = conclusion;
    }

    
    @Column(name="helico_test", nullable=false)
    public String getHelicoTest() {
        return this.helicoTest;
    }
    
    public void setHelicoTest(String helicoTest) {
        this.helicoTest = helicoTest;
    }

    
    @Column(name="acidity_test", nullable=false)
    public String getAcidityTest() {
        return this.acidityTest;
    }
    
    public void setAcidityTest(String acidityTest) {
        this.acidityTest = acidityTest;
    }
    
     public int getPatientId() {
        return patientId;
    }

    public void setPatientId(int patientId) {
        this.patientId = patientId;
    }
    
     public String getProtocol() {
        return protocol;
    }

    public void setProtocol(String protocol) {
        this.protocol = protocol;
    }

    public String getProtocolDescr() {
        return protocolDescr;
    }

    public void setProtocolDescr(String protocolDescr) {
        this.protocolDescr = protocolDescr;
    }
    
    public String toString(){
        return "surveyName = " + surveyName + "; patientId = " +patientId;
    }




}


